export default function createDataImporterContainerProps({
  rootRef,
  canUploadFiles,
  isReadOnlyForEdits,
  canManageAlerts,
  isAdminRole,
  mode,
  previewSource = null,
  deletedDialog,
  columnConfigDialog,
  duplicateDiffDialog,
  duplicateReviewDialog,
  workflowGuideProps,
  summaryCards,
  cardSurfaceClass,
  updatedRowsBanner,
  syncConfigPanelProps,
  coCodeConfigProps,
  monitoringCoDiscrepancyProps,
  monitoringAlertsProps,
  formatDeclarationLabel,
  formatDisplayDate,
  fileActionsProps,
  importPreview,
  errorReasonLabels,
  listControlsPanelProps,
  viewMode,
  tableResultsProps,
  cardResultsProps,
}) {
  return {
    rootRef,
    canUploadFiles,
    isReadOnlyForEdits,
    canManageAlerts,
    isAdminRole,
    mode,
    deletedRowsDialogProps: deletedDialog,
    columnConfigDialogProps: columnConfigDialog,
    duplicateDiffDialogProps: duplicateDiffDialog,
    duplicateReviewDialogProps: duplicateReviewDialog,
    workflowGuideProps,
    summaryCardsProps: {
      summaryCards,
      cardSurfaceClass,
    },
    updatedRowsBannerProps: updatedRowsBanner,
    syncConfigPanelProps,
    coCodeConfigProps,
    monitoringPanelProps: {
      coDiscrepancy: monitoringCoDiscrepancyProps,
      alerts: monitoringAlertsProps,
      formatDeclarationLabel,
      formatDisplayDate,
    },
    fileActionsProps,
    importPreviewSummaryProps: {
      importPreview,
      previewSource,
      errorReasonLabels,
      formatDeclarationLabel,
    },
    listControlsPanelProps,
    resultsPanelProps: {
      viewMode,
      tableProps: tableResultsProps,
      cardProps: cardResultsProps,
    },
  };
}
