import resolveImportEligibility from "@/components/dataImporter/importGate.js";

export default function createDataImporterShellProps({
  columnDraftHidden = new Set(),
  totalConfigColumns = 0,
  isReadOnlyForEdits = true,
  mode = "saved",
  previewSource = null,
  effectivePreviewRows = [],
  importPreview = null,
  canEdit = false,
  rawRowsLength = 0,
  selectedFile = "",
  canViewSavedRows = false,
  canUploadFiles = false,
  canManageSync = false,
  syncPreviewRows = [],
  previewLoading = false,
  syncRunning = false,
  fileInputRef,
  onFileChange,
  onImport,
  onPreviewSync,
  onRunSync,
  onLoadSavedRows,
  onOpenDeletedList,
  selectedPresetId = "",
  savedPresets = [],
  presetBusy = false,
  presetSaving = false,
  presetLoading = false,
  presetError = "",
  appliedPreset = null,
  appliedPresetUpdatedAt = "",
  onSelectPreset,
  onApplySelectedPreset,
  onSavePresetAsNew,
  onOverwriteSelectedPreset,
  onDeleteSelectedPreset,
  onRefreshPresetList,
  onClearPresetError,
  filterDuplicate11 = false,
  hasDuplicate11Rows = false,
  duplicate11GroupCount = 0,
  duplicate11PlannedRemovalCount = 0,
  duplicate11PlannedReviewGroups = 0,
  duplicate11TotalRows = 0,
  filteredKeyCount = 0,
  canAutoReconcile = false,
  onToggleDuplicateFilter,
  onDeleteDuplicates11,
  onAutoApplyLicenseExclusion,
  deleteEnabled = false,
  shouldUseServerSearch = false,
  serverSearchState = null,
  total = 0,
  safePage = 1,
  maxPage = 1,
  viewMode = "table",
  freezeColumnsEnabled = false,
  appliedCardColumns = 0,
  effectiveCardColumns = 0,
  cardGridColumnOptions = [],
  pageSize = 0,
  pageSizeMode = "preset",
  pageSizeCustomInput = "",
  pageSizeOptions = [],
  showDeletedRows = false,
  deletedRowCount = 0,
  canSave,
  onChangeViewMode,
  onChangeFreezeColumnsEnabled,
  onChangeCardGridColumns,
  onChangePageSizeSelect,
  onChangePageSizeCustomInput,
  onToggleShowDeletedRows,
  setPage,
  onSaveAll,
  autoAssignStaff = false,
  upsert11 = false,
  overwrite = false,
  canOverwriteData = false,
  query = "",
  visibleColumnCount = 0,
  totalBaseColumns = 0,
  selectionEnabled = false,
  hasUnsaved = false,
  queryFilterControlsProps = {},
  selectionActionsProps = {},
  onAutoAssignStaffChange,
  onUpsert11Change,
  onOverwriteToggle,
  onOpenColumnConfig,
}) {
  const isSyncPreview = mode === "preview" && previewSource === "sync";
  const columnDraftVisibleCount = Math.max(
    1,
    totalConfigColumns - Math.min(columnDraftHidden.size, totalConfigColumns),
  );

  const importGate = resolveImportEligibility({
    canUploadFiles,
    isReadOnlyForEdits,
    mode,
    previewSource,
    effectivePreviewRows,
    importPreview,
  });
  const derivedCanImport = importGate.canImport;

  const derivedCanSave = canSave ?? (!isReadOnlyForEdits && mode === "saved" && rawRowsLength > 0);
  const canResolveDuplicates11 = deleteEnabled && hasDuplicate11Rows;
  const modeLabel =
    mode === "preview"
      ? isSyncPreview
        ? "Đang rà soát xem trước đồng bộ ECUS"
        : "Đang xem dữ liệu từ file (chưa lưu)"
      : "Đang xem dữ liệu đã lưu";
  const openFilePicker = () => fileInputRef?.current?.click?.();

  const fileActionsProps = {
    fileInputRef,
    onFileChange,
    onOpenFilePicker: openFilePicker,
    onImport,
    onLoadSavedRows,
    onOpenDeletedList,
    isReadOnlyForEdits,
    canEdit,
    canImport: derivedCanImport,
    importDisabledReason: importGate.reason,
    canViewSavedRows,
    selectedFile,
    modeLabel,
  };

  const filterPresetControlsProps = {
    selectedPresetId,
    savedPresets,
    presetBusy,
    presetSaving,
    presetLoading,
    presetError,
    appliedPreset,
    appliedPresetUpdatedAt,
    onSelectPreset,
    onApplySelectedPreset,
    onSavePresetAsNew,
    onOverwriteSelectedPreset,
    onDeleteSelectedPreset,
    onRefreshPresetList,
    onClearPresetError,
  };

  const duplicateWorkflowControlsProps = {
    filterDuplicate11,
    hasDuplicate11Rows,
    canResolveDuplicates11,
    duplicate11GroupCount,
    duplicate11PlannedRemovalCount,
    duplicate11PlannedReviewGroups,
    duplicate11TotalRows,
    canEdit,
    mode,
    filteredKeyCount,
    canAutoReconcile,
    onToggleDuplicateFilter,
    onDeleteDuplicates11,
    onAutoApplyLicenseExclusion,
  };

  const gridToolbarControlsProps = {
    shouldUseServerSearch,
    serverSearchState,
    total,
    safePage,
    maxPage,
    viewMode,
    freezeColumnsEnabled,
    appliedCardColumns,
    effectiveCardColumns,
    cardGridColumnOptions,
    pageSize,
    pageSizeMode,
    pageSizeCustomInput,
    pageSizeOptions,
    showDeletedRows,
    deletedRowCount,
    canEdit,
    canSave: derivedCanSave,
    onChangeViewMode,
    onChangeFreezeColumnsEnabled,
    onChangeCardGridColumns,
    onChangePageSizeSelect,
    onChangePageSizeCustomInput,
    onToggleShowDeletedRows,
    onPreviousPage: () => setPage((pageValue) => Math.max(1, pageValue - 1)),
    onNextPage: () => setPage((pageValue) => Math.min(maxPage, pageValue + 1)),
    onSaveAll,
  };

  const workflowGuideProps = {
    mode,
    canEdit,
    canImport: derivedCanImport,
    importDisabledReason: importGate.reason,
    canSave: derivedCanSave,
    canUploadFiles,
    canManageSync,
    selectedFile,
    previewRowCount: effectivePreviewRows.length,
    syncPreviewRowCount: syncPreviewRows.length,
    previewLoading,
    syncRunning,
    hasRows: rawRowsLength > 0,
    hasUnsaved,
    onOpenFilePicker: openFilePicker,
    onImport,
    onPreviewSync,
    onRunSync,
    onLoadSavedRows,
    onSaveAll,
    previewSource,
  };

  const listControlsPanelProps = {
    mode,
    previewSource,
    total,
    canEdit,
    canOverwriteData,
    autoAssignStaff,
    upsert11,
    overwrite,
    pageSize,
    query,
    visibleColumnCount,
    totalBaseColumns,
    selectionEnabled,
    queryFilterControlsProps,
    filterPresetControlsProps,
    duplicateWorkflowControlsProps,
    gridToolbarControlsProps,
    selectionActionsProps,
    onAutoAssignStaffChange,
    onUpsert11Change,
    onOverwriteToggle,
    onOpenColumnConfig,
  };

  return {
    columnDraftVisibleCount,
    canImport: derivedCanImport,
    importDisabledReason: importGate.reason,
    canSave: derivedCanSave,
    canResolveDuplicates11,
    workflowGuideProps,
    fileActionsProps,
    filterPresetControlsProps,
    duplicateWorkflowControlsProps,
    gridToolbarControlsProps,
    listControlsPanelProps,
  };
}
