export default function createDataImporterResultsProps({
  pageRows = [],
  hiddenColumns = new Set(),
  selectionEnabled = false,
  selectedKeys = [],
  updatedKeySet = new Set(),
  coMismatchKeySet = new Set(),
  duplicate11KeeperSet = new Set(),
  duplicate11DuplicatesSet = new Set(),
  rosterTeams = [],
  agencyOptions = [],
  historyEnabled = false,
  updateEnabled = false,
  deleteEnabled = false,
  buildRowState,
  onToggleSelect,
  onSelectStaff,
  onSelectTeam,
  onSelectAgency,
  onChangeLicenseCount,
  onToggleHistory,
  onSaveRowChanges,
  onDeleteSingle,
  getCoDisplay,
  getKpiDisplay,
  formatDisplayDate,
  formatHistoryTimestamp,
  humanizeDiffKey,
  declHistoryFieldLabels = {},
  StaffComboboxComponent,
  TeamComboboxComponent,
  AgencyComboboxComponent,
  DeclarationStatusDisplayComponent,
  totalColumns = 0,
  frozenOffsets = {},
  frozenHeaderClass = "",
  renderResizeHandle,
  registerHeaderRef,
  getFrozenStyle,
  getColumnStyle,
  columnLabels = {},
  frozenCellClass = "",
  historyIndent = 0,
  onRestoreSingle,
  onHardDeleteSingle,
  cardGridStyle = {},
  ButtonComponent,
}) {
  const sharedResultsProps = {
    pageRows,
    hiddenColumns,
    selectionEnabled,
    selectedKeys,
    updatedKeySet,
    coMismatchKeySet,
    duplicate11KeeperSet,
    duplicate11DuplicatesSet,
    rosterTeams,
    agencyOptions,
    historyEnabled,
    updateEnabled,
    deleteEnabled,
    buildRowState,
    onToggleSelect,
    onSelectStaff,
    onSelectTeam,
    onSelectAgency,
    onChangeLicenseCount,
    onToggleHistory,
    onSaveRowChanges,
    onDeleteSingle,
    getCoDisplay,
    getKpiDisplay,
    formatDisplayDate,
    formatHistoryTimestamp,
    humanizeDiffKey,
    declHistoryFieldLabels,
    StaffComboboxComponent,
    TeamComboboxComponent,
    AgencyComboboxComponent,
    DeclarationStatusDisplayComponent,
  };

  const tableResultsProps = {
    ...sharedResultsProps,
    totalColumns,
    frozenOffsets,
    frozenHeaderClass,
    renderResizeHandle,
    registerHeaderRef,
    getFrozenStyle,
    getColumnStyle,
    columnLabels,
    frozenCellClass,
    historyIndent,
    onRestoreSingle,
    onHardDeleteSingle,
  };

  const cardResultsProps = {
    ...sharedResultsProps,
    cardGridStyle,
    ButtonComponent,
  };

  return {
    sharedResultsProps,
    tableResultsProps,
    cardResultsProps,
  };
}
