export default function createDataImporterDialogProps({
  deletedDialogOpen = false,
  handleDeletedDialogOpenChange,
  deletedRangeLabel = "",
  deletedTotalCount = 0,
  softDeletedCount = 0,
  hardDeletedCount = 0,
  hardDeletedLoading = false,
  hardDeletedError = "",
  handleHardDeletedRetry,
  deletedEntries = [],
  zebraTableBodyClass = "",
  columnConfigOpen = false,
  setColumnConfigOpen,
  columnConfigOptions = [],
  columnDraftHidden = [],
  columnDraftVisibleCount = 0,
  totalConfigColumns = 0,
  isAdminRole = false,
  sensitiveColumnSet = new Set(),
  columnDraftError = "",
  handleToggleColumnDraft,
  handleResetColumnConfig,
  handleApplyColumnConfig,
  duplicateDiffState = {},
  handleDuplicateDiffOpenChange,
  duplicateDiffGroup = null,
  duplicateDiffGroupLabel = "",
  duplicateDiffBaseLabel = "",
  duplicateDiffCompareLabel = "",
  duplicateDiffBaseItem = null,
  duplicateDiffCompareItem = null,
  duplicateDiffChangedCount = 0,
  duplicateDiffGroups = [],
  handleChangeDuplicateDiffBase,
  handleChangeDuplicateDiffCompare,
  handleSwapDuplicateDiff,
  handleCloseDuplicateDiff,
  duplicateReviewOpen = false,
  handleDuplicateReviewOpenChange,
  duplicate11Details = null,
  duplicate11Plan = null,
  duplicate11PlanHasActions = false,
  duplicate11PlannedRemovalCount = 0,
  duplicate11PlannedDeleteGroups = 0,
  duplicate11PlannedReviewGroups = 0,
  duplicateReviewConfirmed = false,
  setDuplicateReviewConfirmed,
  duplicateMergeFields = [],
  handleChangeDuplicateKeeper,
  handleOpenDuplicateDiff,
  handleChangeDuplicateMerge,
  handleChangeDuplicateResolution,
  handleChangeDuplicateNote,
  handleCloseDuplicateReview,
  handleConfirmDuplicateRemoval,
  showUpdatedBanner = false,
  lastSyncUpdated = 0,
  lastSyncRunAtLabel = "",
  updatedPreview = [],
  updatedDeclarations = [],
  formatDeclarationLabel,
  handleSelectUpdated,
  clearSelection,
}) {
  return {
    deletedDialog: {
      open: deletedDialogOpen,
      onOpenChange: handleDeletedDialogOpenChange,
      rangeLabel: deletedRangeLabel,
      totalCount: deletedTotalCount,
      softDeletedCount,
      hardDeletedCount,
      hardDeletedLoading,
      hardDeletedError,
      onRetry: handleHardDeletedRetry,
      entries: deletedEntries,
      tableClassName: zebraTableBodyClass,
    },
    columnConfigDialog: {
      open: columnConfigOpen,
      onOpenChange: setColumnConfigOpen,
      columnOptions: columnConfigOptions,
      hiddenColumnIds: columnDraftHidden,
      visibleCount: columnDraftVisibleCount,
      totalCount: totalConfigColumns,
      isAdminRole,
      sensitiveColumnIds: sensitiveColumnSet,
      errorMessage: columnDraftError,
      onToggleColumn: handleToggleColumnDraft,
      onReset: handleResetColumnConfig,
      onApply: handleApplyColumnConfig,
    },
    duplicateDiffDialog: {
      open: Boolean(duplicateDiffState.open),
      onOpenChange: handleDuplicateDiffOpenChange,
      duplicateDiffGroup,
      duplicateDiffGroupLabel,
      duplicateDiffBaseLabel,
      duplicateDiffCompareLabel,
      duplicateDiffBaseItem,
      duplicateDiffCompareItem,
      duplicateDiffChangedCount,
      duplicateDiffGroups,
      onChangeBase: handleChangeDuplicateDiffBase,
      onChangeCompare: handleChangeDuplicateDiffCompare,
      onSwap: handleSwapDuplicateDiff,
      onClose: handleCloseDuplicateDiff,
    },
    duplicateReviewDialog: {
      open: duplicateReviewOpen,
      onOpenChange: handleDuplicateReviewOpenChange,
      duplicate11Details,
      duplicate11Plan,
      duplicate11PlanHasActions,
      duplicate11PlannedRemovalCount,
      duplicate11PlannedDeleteGroups,
      duplicate11PlannedReviewGroups,
      duplicateReviewConfirmed,
      onConfirmedChange: setDuplicateReviewConfirmed,
      duplicateMergeFields,
      onChangeKeeper: handleChangeDuplicateKeeper,
      onOpenDuplicateDiff: handleOpenDuplicateDiff,
      onChangeMerge: handleChangeDuplicateMerge,
      onChangeResolution: handleChangeDuplicateResolution,
      onChangeNote: handleChangeDuplicateNote,
      onClose: handleCloseDuplicateReview,
      onConfirm: handleConfirmDuplicateRemoval,
    },
    updatedRowsBanner: {
      isAdminRole,
      showUpdatedBanner,
      lastSyncUpdated,
      lastSyncRunAtLabel,
      updatedPreview,
      updatedDeclarations,
      formatDeclarationLabel,
      onSelectUpdated: handleSelectUpdated,
      onClearSelection: clearSelection,
    },
  };
}
