import { Button } from "@/components/ui/button.tsx";
import {
  AgencyCombobox,
  StaffCombobox,
  TeamCombobox,
} from "@/components/dataImporter/DataImporterAssignmentComboboxes.jsx";
import { DeclarationStatusDisplay } from "@/components/dataImporter/DataImporterDeclarationStatus.jsx";
import useDataImporterAssignments from "@/components/dataImporter/useDataImporterAssignments.js";
import useDataImporterLayout from "@/components/dataImporter/useDataImporterLayout.js";
import useDataImporterRowEditing from "@/components/dataImporter/useDataImporterRowEditing.js";
import useDataImporterRowMutations from "@/components/dataImporter/useDataImporterRowMutations.js";
import useDataImporterRowPresentation from "@/components/dataImporter/useDataImporterRowPresentation.js";
import useDataImporterSelectionActions from "@/components/dataImporter/useDataImporterSelectionActions.js";
import useDataImporterSelectionBulkActions from "@/components/dataImporter/useDataImporterSelectionBulkActions.js";
import {
  DECL_HISTORY_FIELD_LABELS,
  IMPORT_TABLE_COLUMN_LABELS,
} from "@/components/dataImporter/dataImporterConfig.js";
import createDataImporterResultsProps from "@/components/dataImporter/dataImporterResultsProps.js";
import { humanizeDiffKey } from "@/components/dataImporter/dataImporterDuplicateDiffUtils.js";
import { formatHistoryTimestamp } from "@/components/dataImporter/dataImporterDuplicateReviewUtils.js";
import { computeKPI } from "@/lib/rules.js";
import { coLabel, coLineCount } from "../../../packages/domain/src/co.js";
import { formatDisplayDate } from "../../../packages/domain/src/format.js";

export default function useDataImporterResultsController({
  actor = "system",
  mode = "source",
  canEdit = false,
  canManageAlerts = false,
  canReviewAlerts = false,
  isReadOnlyForEdits = true,
  shouldUseServerSearch = false,
  rules = null,
  rawRows = [],
  pageRows = [],
  filteredKeys = [],
  selectedKeys = [],
  rowDiffMap = {},
  rowSaveStatus = {},
  rowHistoryEntries = {},
  rowHistoryExpanded = {},
  updatedKeySet = new Set(),
  coMismatchKeySet = new Set(),
  duplicate11KeeperSet = new Set(),
  duplicate11DuplicatesSet = new Set(),
  rosterTeams = [],
  agencyOptions = [],
  columnHiddenSet = new Set(),
  columnWidths = {},
  freezeColumnsEnabled = false,
  cardGridColumns = 3,
  containerWidth = 0,
  visibleColumnCount = 0,
  handleToggleHistory,
  handleSaveRowChanges,
  summarizeLicenseSnapshot,
  handleMarkReviewed,
  handleUnmarkReviewed,
  handleApplyLicenseExclusion,
  keyOfRow,
  normalizeStr,
  normalizeName,
  editingRestrictionMessage = "",
  reviewLockMessage = "",
  blockedEditNoticeRef,
  isRowEditable,
  isRowReviewLocked,
  sanitizeRowUpdates,
  setServerSearchState,
  setHasUnsaved,
  setPage,
  setSelectedKeys,
  setRawRows,
  memberTeamMap = {},
  ensureEditableKeys,
  ensureHardDeleteKeys,
  filterEditableKeys,
  filterHardDeleteKeys,
  loadSavedRows,
  fetchAlerts,
  softDeleteDeclRows,
  hardDeleteDeclRows,
  restoreDeclRows,
  pushAuditLog,
  xlsx,
  xlsxLoader,
  toast,
  registerHeaderRef,
  renderResizeHandle,
}) {
  const { applyEdit } = useDataImporterRowEditing({
    isReadOnlyForEdits,
    mode,
    rules,
    editingRestrictionMessage,
    isRowEditable,
    blockedEditNoticeRef,
    keyOfRow,
    sanitizeRowUpdates,
    shouldUseServerSearch,
    setServerSearchState,
    setHasUnsaved,
    setSelectedKeys,
    setRawRows,
    computeKPI,
  });

  const { handleSelectStaff, handleSelectTeam, handleSelectAgency } = useDataImporterAssignments({
    applyEdit,
    memberTeamMap,
    normalizeStr,
    normalizeName,
  });

  const {
    handleDeleteSelected,
    handleHardDeleteSelected,
    handleDeleteSingle,
    handleHardDeleteSingle,
    handleRestoreSingle,
  } = useDataImporterRowMutations({
    actor,
    mode,
    isReadOnlyForEdits,
    selectedKeys,
    editingRestrictionMessage,
    reviewLockMessage,
    ensureEditableKeys,
    ensureHardDeleteKeys,
    filterEditableKeys,
    filterHardDeleteKeys,
    isRowEditable,
    keyOfRow,
    softDeleteDeclRows,
    hardDeleteDeclRows,
    restoreDeclRows,
    pushAuditLog,
    setHasUnsaved,
    setSelectedKeys,
    loadSavedRows,
    fetchAlerts,
  });

  const selectionEnabled = mode === "saved" && (canEdit || canManageAlerts);
  const updateEnabled = canEdit && mode === "saved" && !columnHiddenSet.has("update");
  const deleteEnabled = canEdit && mode === "saved";
  const historyEnabled = mode === "saved" && !columnHiddenSet.has("history");

  const {
    filteredSelected,
    selectedReviewedCount,
    handleToggleSelect,
    handleClearSelection,
    handleSelectFiltered,
  } = useDataImporterSelectionActions({
    selectionEnabled,
    filteredKeys,
    selectedKeys,
    rawRows,
    keyOfRow,
    setSelectedKeys,
    setPage,
    isReadOnlyForEdits,
    isRowEditable,
    isRowReviewLocked,
    reviewLockMessage,
    editingRestrictionMessage,
    toast,
  });

  const {
    buildRowState,
    handleCardLicenseCountChange,
    getCardCoDisplay,
    getCardKpiDisplay,
  } = useDataImporterRowPresentation({
    isReadOnlyForEdits,
    editingRestrictionMessage,
    reviewLockMessage,
    isRowEditable,
    isRowReviewLocked,
    keyOfRow,
    normalizeStr,
    rowDiffMap,
    rowSaveStatus,
    rowHistoryEntries,
    rowHistoryExpanded,
    applyEdit,
    coLineCount,
    coLabel,
    computeKPI,
    rules,
  });

  const {
    getColumnStyle,
    frozenOffsets,
    getFrozenStyle,
    historyIndent,
    effectiveCardColumns,
    appliedCardColumns,
    cardGridStyle,
    totalColumns,
    frozenHeaderClass,
    frozenCellClass,
  } = useDataImporterLayout({
    columnWidths,
    freezeColumnsEnabled,
    selectionEnabled,
    hiddenColumns: columnHiddenSet,
    cardGridColumns,
    containerWidth,
    visibleColumnCount,
    updateEnabled,
    deleteEnabled,
    historyEnabled,
  });

  const { tableResultsProps, cardResultsProps } = createDataImporterResultsProps({
    pageRows,
    hiddenColumns: columnHiddenSet,
    selectionEnabled,
    selectedKeys,
    updatedKeySet,
    coMismatchKeySet,
    duplicate11KeeperSet,
    duplicate11DuplicatesSet,
    rosterTeams,
    agencyOptions,
    historyEnabled,
    updateEnabled,
    deleteEnabled,
    buildRowState,
    onToggleSelect: handleToggleSelect,
    onSelectStaff: handleSelectStaff,
    onSelectTeam: handleSelectTeam,
    onSelectAgency: handleSelectAgency,
    onChangeLicenseCount: handleCardLicenseCountChange,
    onToggleHistory: handleToggleHistory,
    onSaveRowChanges: handleSaveRowChanges,
    onDeleteSingle: handleDeleteSingle,
    getCoDisplay: getCardCoDisplay,
    getKpiDisplay: getCardKpiDisplay,
    formatDisplayDate,
    formatHistoryTimestamp,
    humanizeDiffKey,
    declHistoryFieldLabels: DECL_HISTORY_FIELD_LABELS,
    StaffComboboxComponent: StaffCombobox,
    TeamComboboxComponent: TeamCombobox,
    AgencyComboboxComponent: AgencyCombobox,
    DeclarationStatusDisplayComponent: DeclarationStatusDisplay,
    totalColumns,
    frozenOffsets,
    frozenHeaderClass,
    renderResizeHandle,
    registerHeaderRef,
    getFrozenStyle,
    getColumnStyle,
    columnLabels: IMPORT_TABLE_COLUMN_LABELS,
    frozenCellClass,
    historyIndent,
    onRestoreSingle: handleRestoreSingle,
    onHardDeleteSingle: handleHardDeleteSingle,
    cardGridStyle,
    ButtonComponent: Button,
  });

  const { selectionActionsProps } = useDataImporterSelectionBulkActions({
    deleteEnabled,
    selectionEnabled,
    selectedKeys,
    selectedReviewedCount,
    canReviewAlerts,
    rawRows,
    filteredKeys,
    filteredSelected,
    shouldUseServerSearch,
    canEdit,
    keyOfRow,
    summarizeLicenseSnapshot,
    formatDisplayDate,
    coLabel,
    coLineCount,
    xlsx,
    xlsxLoader,
    handleSelectFiltered,
    handleMarkReviewed,
    handleUnmarkReviewed,
    handleDeleteSelected,
    handleHardDeleteSelected,
    handleApplyLicenseExclusion,
    handleClearSelection,
  });

  return {
    selectionEnabled,
    deleteEnabled,
    effectiveCardColumns,
    appliedCardColumns,
    tableResultsProps,
    cardResultsProps,
    selectionActionsProps,
  };
}
