import { useCallback, useState } from "react";

import {
  getDeclHistoryForRow,
  getDeclRows,
  getHQAgencies,
  mapHQAgenciesByMST,
  mapMemberNamesToTeams,
  markDeclRowsReviewed,
  normalizeName,
  normalizeStr,
  parseAgencyList,
  previewDeclRows,
  pushImportLog,
  refreshDeclRowsFromServer,
  saveDeclRows,
  sortDeclRows,
  unmarkDeclRowsReviewed,
  getTeamRoster,
} from "@/lib/store.js";
import { detectDateOrder, mapRow } from "@/lib/importer.js";
import {
  getSyncStatus,
  STORAGE_LIMIT_ERROR_MESSAGE,
  subscribeSyncStatus,
} from "@/lib/storageClient.js";
import { loadRules } from "@/lib/rules.js";
import { fetchWithAuth } from "@/auth/localAuth.js";
import useFilterPresets from "@/hooks/useFilterPresets.js";
import { toast } from "@/shared/toast.js";
import { filterDeclRows } from "../../../packages/domain/src/declSearch.js";
import { formatDateRangeLabel, formatDisplayDate, formatDateTime } from "../../../packages/domain/src/format.js";
import useDataImporterActionGuards from "@/components/dataImporter/useDataImporterActionGuards.js";
import buildDataImporterSessionControllerResult from "@/components/dataImporter/buildDataImporterSessionControllerResult.js";
import useDataImporterColumnConfig from "@/components/dataImporter/useDataImporterColumnConfig.jsx";
import useDataImporterDisplayPreferences from "@/components/dataImporter/useDataImporterDisplayPreferences.js";
import useDataImporterEditAccess from "@/components/dataImporter/useDataImporterEditAccess.js";
import useDataImporterFilterPresets from "@/components/dataImporter/useDataImporterFilterPresets.js";
import useDataImporterImportPreview from "@/components/dataImporter/useDataImporterImportPreview.js";
import useDataImporterLicenseSummary from "@/components/dataImporter/useDataImporterLicenseSummary.js";
import useDataImporterListPreferences from "@/components/dataImporter/useDataImporterListPreferences.js";
import useDataImporterRowHistory from "@/components/dataImporter/useDataImporterRowHistory.js";
import { extractDataImporterErrorMessage } from "@/components/dataImporter/dataImporterResponseErrors.js";
import useDataImporterSessionFilters from "@/components/dataImporter/useDataImporterSessionFilters.js";
import useDataImporterSessionSyncBundle from "@/components/dataImporter/useDataImporterSessionSyncBundle.js";
import useDataImporterSyncStatusToast from "@/components/dataImporter/useDataImporterSyncStatusToast.js";
import { buildRosterTeams } from "@/components/dataImporter/dataImporterRowUtils.js";
import {
  ACCEPTED_IMPORT_EXTENSIONS,
  CARD_GRID_COLUMN_OPTIONS,
  CO_FILTER_OPTIONS,
  DATE_RANGE_PRESETS,
  DEFAULT_CARD_GRID_COLUMNS,
  DEFAULT_PAGE_SIZE,
  FILTER_PRESET_SCOPE,
  MAX_IMPORT_FILE_SIZE_BYTES,
  MAX_IMPORT_ROWS,
  SERVER_SEARCH_MAX_PAGE_SIZE,
  SERVER_SEARCH_THRESHOLD,
  VIEW_MODES,
  toDateInputValue,
} from "@/components/dataImporter/dataImporterConfig.js";
import { ensureCOFields, ensureLicenseFields } from "@/components/dataImporter/dataImporterLicenseUtils.js";
import { loadXlsx } from "@/lib/loadXlsx.js";

export default function useDataImporterSessionController({
  currentUser,
  canEdit,
  canImportUpload,
  canManageSync,
  canManageAlerts,
  allowAdminUploadOverride,
  mainSearchHelpTextId,
  fileRef,
  rawRows,
  setRawRows,
  showDeletedRows,
  setShowDeletedRows,
  query,
  setQuery,
  quickMST,
  setQuickMST,
  quickCompany,
  setQuickCompany,
  statusFilters,
  setStatusFilters,
  setPage,
  mode,
  setMode,
  selectedFile,
  setSelectedFile,
  previewSource,
  setPreviewSource,
  syncPreviewMeta,
  setSyncPreviewMeta,
  selectedKeys,
  setSelectedKeys,
  hasUnsaved,
  setHasUnsaved,
  overwrite,
  setOverwrite,
  upsert11,
  autoAssignStaff,
  updateBaselineSnapshot,
  keyOfRow,
}) {
  const actor = currentUser?.username || "guest";
  const {
    pageSize,
    setPageSize,
    pageSizeMode,
    setPageSizeMode,
    pageSizeCustomInput,
    setPageSizeCustomInput,
    viewMode,
    setViewMode,
    freezeColumnsEnabled,
    setFreezeColumnsEnabled,
    cardGridColumns,
    setCardGridColumns,
  } = useDataImporterDisplayPreferences();

  useDataImporterSyncStatusToast({
    getSyncStatus,
    subscribeSyncStatus,
    storageLimitErrorMessage: STORAGE_LIMIT_ERROR_MESSAGE,
    notifyError: toast.error,
  });

  const {
    presets: savedPresets,
    loading: presetLoading,
    error: presetError,
    clearError: clearPresetError,
    refresh: refreshPresetList,
    createPreset: createFilterPreset,
    updatePreset: updateFilterPreset,
    deletePreset: deleteFilterPreset,
  } = useFilterPresets(FILTER_PRESET_SCOPE);

  const [datePreset, setDatePreset] = useState("none");
  const [filterNoStaff, setFilterNoStaff] = useState(false);
  const [filterNoTeam, setFilterNoTeam] = useState(false);
  const [filterDuplicate11, setFilterDuplicate11] = useState(false);
  const [coFilterMode, setCoFilterMode] = useState("all");
  const [coFilterMin, setCoFilterMin] = useState(5);
  const [searchRange, setSearchRange] = useState({ from: "", to: "" });
  const [rules, setRules] = useState(() => loadRules());
  const [rowSaveStatus, setRowSaveStatus] = useState({});

  const {
    rowHistoryExpanded,
    rowHistoryEntries,
    setRowHistoryExpanded,
    setRowHistoryEntries,
    refreshRowHistory,
    handleToggleHistory,
  } = useDataImporterRowHistory({
    getDeclHistoryForRow,
  });

  const isReadOnlyForEdits = !canEdit;
  const canReviewAlerts = canEdit || canManageAlerts;
  const canViewSavedRows = canEdit || canManageAlerts || canManageSync || canImportUpload;

  const {
    agencyOptions,
    blockedEditNoticeRef,
    canAutoReconcile,
    editingRestrictionMessage,
    isAdminRole,
    isRowEditable,
    memberTeamMap,
    rosterTeams,
    sanitizeRowUpdates,
  } = useDataImporterEditAccess({
    currentUser,
    canEdit,
    rawRows,
    getTeamRoster,
    buildRosterTeams,
    mapMemberNamesToTeams,
    getHQAgencies,
    parseAgencyList,
    normalizeStr,
    normalizeName,
  });

  const {
    columnWidths,
    columnConfigOpen,
    columnDraftHidden,
    columnDraftError,
    columnHiddenSet,
    totalBaseColumns,
    totalConfigColumns,
    visibleColumnCount,
    setColumnConfigOpen,
    setColumnDraftHidden,
    setColumnDraftError,
    registerHeaderRef,
    renderResizeHandle,
    handleToggleColumnDraft,
    handleApplyColumnConfig,
    handleResetColumnConfig,
  } = useDataImporterColumnConfig({
    actor,
    isAdminRole,
  });

  const reviewLockMessage =
    "Tờ khai đã được rà soát. Chỉ quản trị viên mới có thể chỉnh sửa hoặc xóa.";

  const isRowReviewLocked = useCallback(
    (row) => !!(row && typeof row === "object" && row.reviewed) && !isAdminRole,
    [isAdminRole],
  );

  const {
    deletedRowCount,
    baseFilterInputs,
    normalizedFilters,
    deletedDialogOpen,
    hardDeletedLoading,
    hardDeletedError,
    deletedEntries,
    softDeletedCount,
    hardDeletedCount,
    deletedTotalCount,
    deletedRangeLabel,
    openDeletedDialog,
    handleDeletedDialogOpenChange,
    handleHardDeletedRetry,
    shouldUseServerSearch,
    pageResetKey,
    queryFilterControlsProps,
  } = useDataImporterSessionFilters({
    rawRows,
    mode,
    pageSize,
    query,
    quickMST,
    quickCompany,
    statusFilters,
    searchRange,
    filterNoStaff,
    filterNoTeam,
    filterDuplicate11,
    coFilterMode,
    coFilterMin,
    showDeletedRows,
    fetchWithAuth,
    filterDeclRows,
    keyOfRow,
    extractErrorMessage: extractDataImporterErrorMessage,
    formatDateTime,
    formatDisplayDate,
    formatDateRangeLabel,
    mainSearchHelpTextId,
    datePreset,
    setQuery,
    setPage,
    setDatePreset,
    setSearchRange,
    setFilterNoStaff,
    setFilterNoTeam,
    setCoFilterMode,
    setCoFilterMin,
  });

  const { effectivePreviewRows, canUploadFiles, canOverwriteData, importPreview } =
    useDataImporterImportPreview({
      rawRows,
      upsert11,
      mode,
      previewSource,
      overwrite,
      actor,
      canImportUpload,
      allowAdminUploadOverride,
      isAdminRole,
      syncPreviewMeta,
      previewDeclRows,
      setOverwrite,
    });
  const {
    handleOpenColumnConfig,
    handleToolbarViewModeChange,
    handleToolbarFreezeColumnsEnabledChange,
    handleToolbarCardGridColumnsChange,
    handleToolbarPageSizeSelect,
    handleToolbarPageSizeCustomInput,
    handleToolbarToggleShowDeletedRows,
    handleOverwriteToggle,
  } = useDataImporterListPreferences({
    columnHiddenSet,
    pageSize,
    canOverwriteData,
    defaultPageSize: DEFAULT_PAGE_SIZE,
    maxPageSize: SERVER_SEARCH_MAX_PAGE_SIZE,
    viewModes: VIEW_MODES,
    cardGridColumnOptions: CARD_GRID_COLUMN_OPTIONS,
    defaultCardGridColumns: DEFAULT_CARD_GRID_COLUMNS,
    setColumnDraftHidden,
    setColumnDraftError,
    setColumnConfigOpen,
    setPageSizeMode,
    setPageSizeCustomInput,
    setPage,
    setPageSize,
    setViewMode,
    setFreezeColumnsEnabled,
    setCardGridColumns,
    setShowDeletedRows,
    setOverwrite,
  });

  const { filterEditableKeys, filterHardDeleteKeys, ensureEditableKeys, ensureHardDeleteKeys } =
    useDataImporterActionGuards({
      rawRows,
      keyOfRow,
      isRowEditable,
      isRowReviewLocked,
      editingRestrictionMessage,
      reviewLockMessage,
    });
  const {
    selectedPresetId,
    appliedPreset,
    appliedPresetUpdatedAt,
    presetSaving,
    presetBusy,
    handleSelectPreset,
    handleApplySelectedPreset,
    handleSavePresetAsNew,
    handleOverwriteSelectedPreset,
    handleDeleteSelectedPreset,
    handleRefreshPresetList,
  } = useDataImporterFilterPresets({
    savedPresets,
    presetLoading,
    clearError: clearPresetError,
    refreshPresetList,
    createFilterPreset,
    updateFilterPreset,
    deleteFilterPreset,
    datePreset,
    query,
    quickMST,
    quickCompany,
    statusFilters,
    searchRange,
    filterNoStaff,
    filterNoTeam,
    filterDuplicate11,
    coFilterMode,
    coFilterMin,
    setDatePreset,
    setQuery,
    setQuickMST,
    setQuickCompany,
    setStatusFilters,
    setSearchRange,
    setFilterNoStaff,
    setFilterNoTeam,
    setFilterDuplicate11,
    setCoFilterMode,
    setCoFilterMin,
    setPage,
  });
  const {
    licenseExcludeSet,
    licenseAgencyExcludeMap,
    getLicenseExcludeSetForRow,
    summarizeLicenseSnapshot,
  } = useDataImporterLicenseSummary({ rules });
  const {
    coCodeConfig,
    coCodeForm,
    setCoCodeForm,
    coCodeLoading,
    coCodeSaving,
    coCodeError,
    coCodeMessage,
    handleSaveCoCodeConfig,
    handleResetCoCodeForm,
    handleRefreshCoCodeConfig,
    coCodeUpdatedLabel,
    coDiscrepancyState,
    coDiscrepancyForm,
    setCoDiscrepancyForm,
    coDiscrepancyRange,
    setCoDiscrepancyRange,
    coDiscrepancyLoading,
    coDiscrepancySaving,
    coDiscrepancyRunning,
    coDiscrepancyError,
    coDiscrepancyMessage,
    handleSaveCoDiscrepancyConfig,
    handleResetCoDiscrepancyForm,
    handleRunCoDiscrepancy,
    handleRefreshCoDiscrepancy,
    coMismatchKeySet,
    coMismatchPreview,
    coMismatchCount,
    coCheckedCount,
    coMismatchLimited,
    coDiscrepancyRangeLabel,
    coDiscrepancyLastRunLabel,
    coDiscrepancyStatusLabel,
    loadSavedRows,
    syncConfig,
    syncForm,
    setSyncForm,
    syncLoading,
    syncRunning,
    syncMessage,
    syncError,
    manualRange,
    handleManualRangeChange,
    alertSummary,
    alertLoading,
    statusInfo,
    statusLoading,
    statusError,
    previewRows,
    previewLimited,
    previewLoading,
    previewError,
    previewRangeInfo,
    previewRangeLabel,
    previewConflictSummary,
    previewConflictWarningActive,
    mstFilterNotice,
    syncPreflightChecks,
    syncPreflightSummary,
    syncActivityLog,
    syncHistory,
    syncResumeJob,
    syncResumeLabel,
    fetchSyncConfig,
    fetchSyncStatus,
    fetchAlerts,
    handleSaveSyncConfig,
    handleRunSync,
    handleResumeSync,
    handlePreviewSync,
    handleFileChange,
    handleImport,
    applyRangePreset,
    handleRefreshAlerts,
    handleMarkReviewed,
    handleUnmarkReviewed,
    alertEntries,
    outstandingAlerts,
    summaryCards,
    lastAlertEvaluated,
    syncLastRunLabel,
    lastSyncSummary,
    lastSyncRangeLabel,
    lastSyncRunAtLabel,
  } = useDataImporterSessionSyncBundle({
    actor,
    canManageSync,
    canReviewAlerts,
    canUploadFiles,
    isReadOnlyForEdits,
    isAdminRole,
    hasUnsaved,
    mode,
    rawRows,
    selectedKeys,
    selectedFile,
    previewSource,
    effectivePreviewRows,
    importPreview,
    canOverwriteData,
    overwrite,
    autoAssignStaff,
    showDeletedRows,
    fileRef,
    loadRules,
    getDeclRows,
    sortDeclRows,
    ensureLicenseFields,
    ensureCOFields,
    updateBaselineSnapshot,
    setRules,
    setRawRows,
    setRowSaveStatus,
    setRowHistoryExpanded,
    setRowHistoryEntries,
    setMode,
    setPage,
    setQuery,
    setSelectedFile,
    setPreviewSource,
    setSyncPreviewMeta,
    setFilterNoStaff,
    setFilterNoTeam,
    setFilterDuplicate11,
    setCoFilterMode,
    setCoFilterMin,
    setSelectedKeys,
    setHasUnsaved,
    extractErrorMessage: extractDataImporterErrorMessage,
    fetchWithAuth,
    refreshDeclRowsFromServer,
    getTeamRoster,
    mapMemberNamesToTeams,
    mapHQAgenciesByMST,
    detectDateOrder,
    mapRow,
    saveDeclRows,
    pushImportLog,
    xlsxLoader: loadXlsx,
    FileReaderCtor: typeof FileReader === "function" ? FileReader : null,
    toast,
    acceptedImportExtensions: ACCEPTED_IMPORT_EXTENSIONS,
    maxImportFileSizeBytes: MAX_IMPORT_FILE_SIZE_BYTES,
    maxImportRows: MAX_IMPORT_ROWS,
    ensureEditableKeys,
    keyOfRow,
    markDeclRowsReviewed,
    unmarkDeclRowsReviewed,
    formatDateRangeLabel,
    formatDisplayDate,
    toDateInputValue,
  });

  return buildDataImporterSessionControllerResult({
    identity: {
      actor,
      rules,
      setRules,
    },
    rowHistory: {
      rowSaveStatus,
      setRowSaveStatus,
      rowHistoryExpanded,
      rowHistoryEntries,
      setRowHistoryExpanded,
      setRowHistoryEntries,
      refreshRowHistory,
      handleToggleHistory,
    },
    access: {
      isReadOnlyForEdits,
      canReviewAlerts,
      canViewSavedRows,
      agencyOptions,
      blockedEditNoticeRef,
      canAutoReconcile,
      editingRestrictionMessage,
      isAdminRole,
      isRowEditable,
      memberTeamMap,
      rosterTeams,
      sanitizeRowUpdates,
      reviewLockMessage,
      isRowReviewLocked,
    },
    columnConfig: {
      columnWidths,
      columnConfigOpen,
      columnDraftHidden,
      columnDraftError,
      columnHiddenSet,
      totalBaseColumns,
      totalConfigColumns,
      visibleColumnCount,
      setColumnConfigOpen,
      setColumnDraftHidden,
      setColumnDraftError,
      registerHeaderRef,
      renderResizeHandle,
      handleToggleColumnDraft,
      handleApplyColumnConfig,
      handleResetColumnConfig,
    },
    filters: {
      filterDuplicate11,
      setFilterDuplicate11,
      deletedRowCount,
      baseFilterInputs,
      normalizedFilters,
      deletedDialogOpen,
      hardDeletedLoading,
      hardDeletedError,
      deletedEntries,
      softDeletedCount,
      hardDeletedCount,
      deletedTotalCount,
      deletedRangeLabel,
      openDeletedDialog,
      handleDeletedDialogOpenChange,
      handleHardDeletedRetry,
      shouldUseServerSearch,
      pageResetKey,
    },
    preview: {
      effectivePreviewRows,
      canUploadFiles,
      canOverwriteData,
      importPreview,
    },
    listPreferences: {
      pageSize,
      setPageSize,
      pageSizeMode,
      setPageSizeMode,
      pageSizeCustomInput,
      setPageSizeCustomInput,
      viewMode,
      setViewMode,
      freezeColumnsEnabled,
      setFreezeColumnsEnabled,
      cardGridColumns,
      setCardGridColumns,
      handleOpenColumnConfig,
      handleToolbarViewModeChange,
      handleToolbarFreezeColumnsEnabledChange,
      handleToolbarCardGridColumnsChange,
      handleToolbarPageSizeSelect,
      handleToolbarPageSizeCustomInput,
      handleToolbarToggleShowDeletedRows,
      handleOverwriteToggle,
    },
    actionGuards: {
      filterEditableKeys,
      filterHardDeleteKeys,
      ensureEditableKeys,
      ensureHardDeleteKeys,
    },
    presets: {
      selectedPresetId,
      appliedPreset,
      appliedPresetUpdatedAt,
      presetSaving,
      presetBusy,
      savedPresets,
      presetLoading,
      presetError,
      clearPresetError,
      handleSelectPreset,
      handleApplySelectedPreset,
      handleSavePresetAsNew,
      handleOverwriteSelectedPreset,
      handleDeleteSelectedPreset,
      handleRefreshPresetList,
    },
    license: {
      licenseExcludeSet,
      licenseAgencyExcludeMap,
      getLicenseExcludeSetForRow,
      summarizeLicenseSnapshot,
    },
    sync: {
      coCodeConfig,
      coCodeForm,
      setCoCodeForm,
      coCodeLoading,
      coCodeSaving,
      coCodeError,
      coCodeMessage,
      handleSaveCoCodeConfig,
      handleResetCoCodeForm,
      handleRefreshCoCodeConfig,
      coCodeUpdatedLabel,
      coDiscrepancyState,
      coDiscrepancyForm,
      setCoDiscrepancyForm,
      coDiscrepancyRange,
      setCoDiscrepancyRange,
      coDiscrepancyLoading,
      coDiscrepancySaving,
      coDiscrepancyRunning,
      coDiscrepancyError,
      coDiscrepancyMessage,
      handleSaveCoDiscrepancyConfig,
      handleResetCoDiscrepancyForm,
      handleRunCoDiscrepancy,
      handleRefreshCoDiscrepancy,
      coMismatchKeySet,
      coMismatchPreview,
      coMismatchCount,
      coCheckedCount,
      coMismatchLimited,
      coDiscrepancyRangeLabel,
      coDiscrepancyLastRunLabel,
      coDiscrepancyStatusLabel,
      loadSavedRows,
      syncConfig,
      syncForm,
      setSyncForm,
      syncLoading,
      syncRunning,
      syncMessage,
      syncError,
      manualRange,
      handleManualRangeChange,
      alertSummary,
      alertLoading,
      statusInfo,
      statusLoading,
      statusError,
      previewRows,
      previewLimited,
      previewLoading,
      previewError,
      previewRangeInfo,
      previewRangeLabel,
      previewConflictSummary,
      previewConflictWarningActive,
      mstFilterNotice,
      syncPreflightChecks,
      syncPreflightSummary,
      syncActivityLog,
      syncHistory,
      syncResumeJob,
      syncResumeLabel,
      fetchSyncConfig,
      fetchSyncStatus,
      fetchAlerts,
      handleSaveSyncConfig,
      handleRunSync,
      handleResumeSync,
      handlePreviewSync,
      handleFileChange,
      handleImport,
      applyRangePreset,
      handleRefreshAlerts,
      handleMarkReviewed,
      handleUnmarkReviewed,
      alertEntries,
      outstandingAlerts,
      summaryCards,
      lastAlertEvaluated,
      syncLastRunLabel,
      lastSyncSummary,
      lastSyncRangeLabel,
      lastSyncRunAtLabel,
    },
    queryFilters: {
      queryFilterControlsProps,
    },
  });
}
