import { useCallback, useMemo, useState } from "react";
import * as XLSX from "xlsx";

import {
  getDeclHistoryForRow,
  getDeclRows,
  getHQAgencies,
  mapHQAgenciesByMST,
  mapMemberNamesToTeams,
  markDeclRowsReviewed,
  normalizeName,
  normalizeStr,
  parseAgencyList,
  previewDeclRows,
  pushImportLog,
  refreshDeclRowsFromServer,
  saveDeclRows,
  sortDeclRows,
  unmarkDeclRowsReviewed,
  getTeamRoster,
} from "@/lib/store.js";
import { detectDateOrder, mapRow } from "@/lib/importer.js";
import {
  getSyncStatus,
  STORAGE_LIMIT_ERROR_MESSAGE,
  subscribeSyncStatus,
} from "@/lib/storageClient.js";
import { loadRules } from "@/lib/rules.js";
import { fetchWithAuth } from "@/auth/localAuth.js";
import useFilterPresets from "@/hooks/useFilterPresets.js";
import { toast } from "@/shared/toast.js";
import { coLineCount } from "../../../packages/domain/src/co.js";
import { filterDeclRows } from "../../../packages/domain/src/declSearch.js";
import { formatDateRangeLabel, formatDisplayDate, formatDateTime } from "../../../packages/domain/src/format.js";
import useDataImporterActionGuards from "@/components/dataImporter/useDataImporterActionGuards.js";
import useDataImporterCoMonitoring from "@/components/dataImporter/useDataImporterCoMonitoring.js";
import useDataImporterColumnConfig from "@/components/dataImporter/useDataImporterColumnConfig.jsx";
import useDataImporterDeletedRows from "@/components/dataImporter/useDataImporterDeletedRows.js";
import useDataImporterDisplayPreferences from "@/components/dataImporter/useDataImporterDisplayPreferences.js";
import useDataImporterEditAccess from "@/components/dataImporter/useDataImporterEditAccess.js";
import useDataImporterFilterPresets from "@/components/dataImporter/useDataImporterFilterPresets.js";
import useDataImporterImportPreview from "@/components/dataImporter/useDataImporterImportPreview.js";
import { buildDataImporterCoFilterSummary } from "@/components/dataImporter/dataImporterCoFilterSummary.js";
import useDataImporterLicenseSummary from "@/components/dataImporter/useDataImporterLicenseSummary.js";
import useDataImporterListPreferences from "@/components/dataImporter/useDataImporterListPreferences.js";
import useDataImporterQueryFilters from "@/components/dataImporter/useDataImporterQueryFilters.js";
import useDataImporterRowHistory from "@/components/dataImporter/useDataImporterRowHistory.js";
import { buildDataImporterPageResetKey, buildDataImporterSessionFilterState, buildDataImporterSessionRowState } from "@/components/dataImporter/dataImporterSessionDerivedState.js";
import { extractDataImporterErrorMessage } from "@/components/dataImporter/dataImporterResponseErrors.js";
import useDataImporterSyncStatusToast from "@/components/dataImporter/useDataImporterSyncStatusToast.js";
import useDataImporterWorkflowSession from "@/components/dataImporter/useDataImporterWorkflowSession.js";
import { buildRosterTeams } from "@/components/dataImporter/dataImporterRowUtils.js";
import {
  ACCEPTED_IMPORT_EXTENSIONS,
  CARD_GRID_COLUMN_OPTIONS,
  CO_FILTER_OPTIONS,
  DATE_RANGE_PRESETS,
  DEFAULT_CARD_GRID_COLUMNS,
  DEFAULT_PAGE_SIZE,
  FILTER_PRESET_SCOPE,
  MAX_IMPORT_FILE_SIZE_BYTES,
  MAX_IMPORT_ROWS,
  SERVER_SEARCH_MAX_PAGE_SIZE,
  SERVER_SEARCH_THRESHOLD,
  VIEW_MODES,
  toDateInputValue,
} from "@/components/dataImporter/dataImporterConfig.js";
import { ensureCOFields, ensureLicenseFields } from "@/components/dataImporter/dataImporterLicenseUtils.js";

export default function useDataImporterSessionController({
  currentUser,
  canEdit,
  canImportUpload,
  canManageSync,
  canManageAlerts,
  allowAdminUploadOverride,
  mainSearchHelpTextId,
  fileRef,
  rawRows,
  setRawRows,
  showDeletedRows,
  setShowDeletedRows,
  query,
  setQuery,
  quickMST,
  setQuickMST,
  quickCompany,
  setQuickCompany,
  statusFilters,
  setStatusFilters,
  setPage,
  mode,
  setMode,
  selectedFile,
  setSelectedFile,
  previewSource,
  setPreviewSource,
  selectedKeys,
  setSelectedKeys,
  hasUnsaved,
  setHasUnsaved,
  overwrite,
  setOverwrite,
  upsert11,
  autoAssignStaff,
  updateBaselineSnapshot,
  keyOfRow,
}) {
  const actor = currentUser?.username || "guest";
  const {
    pageSize,
    setPageSize,
    pageSizeMode,
    setPageSizeMode,
    pageSizeCustomInput,
    setPageSizeCustomInput,
    viewMode,
    setViewMode,
    freezeColumnsEnabled,
    setFreezeColumnsEnabled,
    cardGridColumns,
    setCardGridColumns,
  } = useDataImporterDisplayPreferences();

  useDataImporterSyncStatusToast({
    getSyncStatus,
    subscribeSyncStatus,
    storageLimitErrorMessage: STORAGE_LIMIT_ERROR_MESSAGE,
    notifyError: toast.error,
  });

  const {
    presets: savedPresets,
    loading: presetLoading,
    error: presetError,
    clearError: clearPresetError,
    refresh: refreshPresetList,
    createPreset: createFilterPreset,
    updatePreset: updateFilterPreset,
    deletePreset: deleteFilterPreset,
  } = useFilterPresets(FILTER_PRESET_SCOPE);

  const [datePreset, setDatePreset] = useState("none");
  const [filterNoStaff, setFilterNoStaff] = useState(false);
  const [filterNoTeam, setFilterNoTeam] = useState(false);
  const [filterDuplicate11, setFilterDuplicate11] = useState(false);
  const [coFilterMode, setCoFilterMode] = useState("all");
  const [coFilterMin, setCoFilterMin] = useState(5);
  const [searchRange, setSearchRange] = useState({ from: "", to: "" });
  const [rules, setRules] = useState(() => loadRules());
  const [rowSaveStatus, setRowSaveStatus] = useState({});

  const {
    rowHistoryExpanded,
    rowHistoryEntries,
    setRowHistoryExpanded,
    setRowHistoryEntries,
    refreshRowHistory,
    handleToggleHistory,
  } = useDataImporterRowHistory({
    getDeclHistoryForRow,
  });

  const isReadOnlyForEdits = !canEdit;
  const canReviewAlerts = canEdit || canManageAlerts;
  const canViewSavedRows = canEdit || canManageAlerts || canManageSync || canImportUpload;

  const {
    agencyOptions,
    blockedEditNoticeRef,
    canAutoReconcile,
    editingRestrictionMessage,
    isAdminRole,
    isRowEditable,
    memberTeamMap,
    rosterTeams,
    sanitizeRowUpdates,
  } = useDataImporterEditAccess({
    currentUser,
    canEdit,
    rawRows,
    getTeamRoster,
    buildRosterTeams,
    mapMemberNamesToTeams,
    getHQAgencies,
    parseAgencyList,
    normalizeStr,
    normalizeName,
  });

  const {
    columnWidths,
    columnConfigOpen,
    columnDraftHidden,
    columnDraftError,
    columnHiddenSet,
    totalBaseColumns,
    totalConfigColumns,
    visibleColumnCount,
    setColumnConfigOpen,
    setColumnDraftHidden,
    setColumnDraftError,
    registerHeaderRef,
    renderResizeHandle,
    handleToggleColumnDraft,
    handleApplyColumnConfig,
    handleResetColumnConfig,
  } = useDataImporterColumnConfig({
    actor,
    isAdminRole,
  });

  const reviewLockMessage =
    "Tờ khai đã được rà soát. Chỉ quản trị viên mới có thể chỉnh sửa hoặc xóa.";

  const isRowReviewLocked = useCallback(
    (row) => !!(row && typeof row === "object" && row.reviewed) && !isAdminRole,
    [isAdminRole],
  );

  const normalizedQuickMST = useMemo(() => normalizeStr(quickMST), [quickMST]);
  const normalizedQuickCompany = useMemo(() => normalizeStr(quickCompany), [quickCompany]);

  const { coThreshold, baseFilterInputs, normalizedFilters } = useMemo(
    () =>
      buildDataImporterSessionFilterState({
        pageSize,
        query,
        quickMST,
        quickCompany,
        normalizedQuickMST,
        normalizedQuickCompany,
        statusFilters,
        searchRange,
        filterNoStaff,
        filterNoTeam,
        filterDuplicate11,
        coFilterMode,
        coFilterMin,
        showDeletedRows,
      }),
    [
      pageSize,
      query,
      quickMST,
      quickCompany,
      normalizedQuickMST,
      normalizedQuickCompany,
      statusFilters,
      searchRange,
      filterNoStaff,
      filterNoTeam,
      filterDuplicate11,
      coFilterMode,
      coFilterMin,
      showDeletedRows,
    ],
  );

  const { deletedRowCount, softDeletedRows, shouldUseServerSearch } = useMemo(
    () =>
      buildDataImporterSessionRowState({
        rawRows,
        mode,
        baseFilterInputs,
        serverSearchThreshold: SERVER_SEARCH_THRESHOLD,
      }),
    [rawRows, mode, baseFilterInputs],
  );

  const pageResetKey = useMemo(
    () =>
      buildDataImporterPageResetKey({
        pageSize,
        quickMST,
        quickCompany,
        statusFilters,
        searchRange,
        filterNoStaff,
        filterNoTeam,
        filterDuplicate11,
        coFilterMode,
        coThreshold,
        shouldUseServerSearch,
        showDeletedRows,
      }),
    [
      pageSize,
      quickMST,
      quickCompany,
      statusFilters,
      searchRange,
      filterNoStaff,
      filterNoTeam,
      filterDuplicate11,
      coFilterMode,
      coThreshold,
      shouldUseServerSearch,
      showDeletedRows,
    ],
  );

  const {
    deletedDialogOpen,
    hardDeletedLoading,
    hardDeletedError,
    deletedEntries,
    softDeletedCount,
    hardDeletedCount,
    deletedTotalCount,
    deletedRangeLabel,
    openDeletedDialog,
    handleDeletedDialogOpenChange,
    handleHardDeletedRetry,
  } = useDataImporterDeletedRows({
    searchRange,
    softDeletedRows,
    baseFilterInputs,
    fetchWithAuth,
    filterDeclRows,
    keyOfRow,
    extractErrorMessage: extractDataImporterErrorMessage,
    formatDateTime,
    formatDisplayDate,
    formatDateRangeLabel,
  });

  const { effectivePreviewRows, canUploadFiles, canOverwriteData, importPreview } =
    useDataImporterImportPreview({
      rawRows,
      upsert11,
      mode,
      previewSource,
      overwrite,
      actor,
      canImportUpload,
      allowAdminUploadOverride,
      isAdminRole,
      previewDeclRows,
      setOverwrite,
    });
  const {
    handleOpenColumnConfig,
    handleToolbarViewModeChange,
    handleToolbarFreezeColumnsEnabledChange,
    handleToolbarCardGridColumnsChange,
    handleToolbarPageSizeSelect,
    handleToolbarPageSizeCustomInput,
    handleToolbarToggleShowDeletedRows,
    handleOverwriteToggle,
  } = useDataImporterListPreferences({
    columnHiddenSet,
    pageSize,
    canOverwriteData,
    defaultPageSize: DEFAULT_PAGE_SIZE,
    maxPageSize: SERVER_SEARCH_MAX_PAGE_SIZE,
    viewModes: VIEW_MODES,
    cardGridColumnOptions: CARD_GRID_COLUMN_OPTIONS,
    defaultCardGridColumns: DEFAULT_CARD_GRID_COLUMNS,
    setColumnDraftHidden,
    setColumnDraftError,
    setColumnConfigOpen,
    setPageSizeMode,
    setPageSizeCustomInput,
    setPage,
    setPageSize,
    setViewMode,
    setFreezeColumnsEnabled,
    setCardGridColumns,
    setShowDeletedRows,
    setOverwrite,
  });

  const { filterEditableKeys, filterHardDeleteKeys, ensureEditableKeys, ensureHardDeleteKeys } =
    useDataImporterActionGuards({
      rawRows,
      keyOfRow,
      isRowEditable,
      isRowReviewLocked,
      editingRestrictionMessage,
      reviewLockMessage,
    });
  const {
    selectedPresetId,
    appliedPreset,
    appliedPresetUpdatedAt,
    presetSaving,
    presetBusy,
    handleSelectPreset,
    handleApplySelectedPreset,
    handleSavePresetAsNew,
    handleOverwriteSelectedPreset,
    handleDeleteSelectedPreset,
    handleRefreshPresetList,
  } = useDataImporterFilterPresets({
    savedPresets,
    presetLoading,
    clearError: clearPresetError,
    refreshPresetList,
    createFilterPreset,
    updateFilterPreset,
    deleteFilterPreset,
    datePreset,
    query,
    quickMST,
    quickCompany,
    statusFilters,
    searchRange,
    filterNoStaff,
    filterNoTeam,
    filterDuplicate11,
    coFilterMode,
    coFilterMin,
    setDatePreset,
    setQuery,
    setQuickMST,
    setQuickCompany,
    setStatusFilters,
    setSearchRange,
    setFilterNoStaff,
    setFilterNoTeam,
    setFilterDuplicate11,
    setCoFilterMode,
    setCoFilterMin,
    setPage,
  });
  const {
    licenseExcludeSet,
    licenseAgencyExcludeMap,
    getLicenseExcludeSetForRow,
    summarizeLicenseSnapshot,
  } = useDataImporterLicenseSummary({ rules });
  const {
    coCodeConfig,
    coCodeForm,
    setCoCodeForm,
    coCodeLoading,
    coCodeSaving,
    coCodeError,
    coCodeMessage,
    handleSaveCoCodeConfig,
    handleResetCoCodeForm,
    handleRefreshCoCodeConfig,
    coCodeUpdatedLabel,
    coDiscrepancyState,
    coDiscrepancyForm,
    setCoDiscrepancyForm,
    coDiscrepancyRange,
    setCoDiscrepancyRange,
    coDiscrepancyLoading,
    coDiscrepancySaving,
    coDiscrepancyRunning,
    coDiscrepancyError,
    coDiscrepancyMessage,
    handleSaveCoDiscrepancyConfig,
    handleResetCoDiscrepancyForm,
    handleRunCoDiscrepancy,
    handleRefreshCoDiscrepancy,
    coMismatchKeySet,
    coMismatchPreview,
    coMismatchCount,
    coCheckedCount,
    coMismatchLimited,
    coDiscrepancyRangeLabel,
    coDiscrepancyLastRunLabel,
    coDiscrepancyStatusLabel,
  } = useDataImporterCoMonitoring({
    canManageSync,
    fetchWithAuth,
    extractErrorMessage: extractDataImporterErrorMessage,
  });
  const {
    loadSavedRows,
    syncConfig,
    syncForm,
    setSyncForm,
    syncLoading,
    syncRunning,
    syncMessage,
    syncError,
    manualRange,
    handleManualRangeChange,
    alertSummary,
    alertLoading,
    statusInfo,
    statusLoading,
    statusError,
    previewRows,
    previewLimited,
    previewLoading,
    previewError,
    previewRangeInfo,
    previewRangeLabel,
    mstFilterNotice,
    fetchSyncConfig,
    fetchSyncStatus,
    fetchAlerts,
    handleSaveSyncConfig,
    handleRunSync,
    handlePreviewSync,
    handleFileChange,
    handleImport,
    applyRangePreset,
    handleRefreshAlerts,
    handleMarkReviewed,
    handleUnmarkReviewed,
    outstandingAlerts,
    summaryCards,
    lastAlertEvaluated,
    syncLastRunLabel,
    lastSyncSummary,
    lastSyncRangeLabel,
    lastSyncRunAtLabel,
  } = useDataImporterWorkflowSession({
    actor,
    canManageSync,
    canReviewAlerts,
    canUploadFiles,
    isReadOnlyForEdits,
    isAdminRole,
    hasUnsaved,
    mode,
    rawRows,
    selectedKeys,
    selectedFile,
    previewSource,
    effectivePreviewRows,
    importPreview,
    canOverwriteData,
    overwrite,
    autoAssignStaff,
    showDeletedRows,
    fileRef,
    loadRules,
    getDeclRows,
    sortDeclRows,
    ensureLicenseFields,
    ensureCOFields,
    updateBaselineSnapshot,
    setRules,
    setRawRows,
    setRowSaveStatus,
    setRowHistoryExpanded,
    setRowHistoryEntries,
    setMode,
    setPage,
    setQuery,
    setSelectedFile,
    setPreviewSource,
    setFilterNoStaff,
    setFilterNoTeam,
    setFilterDuplicate11,
    setCoFilterMode,
    setCoFilterMin,
    setSelectedKeys,
    setHasUnsaved,
    handleRefreshCoDiscrepancy,
    fetchWithAuth,
    refreshDeclRowsFromServer,
    getTeamRoster,
    mapMemberNamesToTeams,
    mapHQAgenciesByMST,
    detectDateOrder,
    mapRow,
    saveDeclRows,
    pushImportLog,
    xlsx: XLSX,
    FileReaderCtor: typeof FileReader === "function" ? FileReader : null,
    toast,
    acceptedImportExtensions: ACCEPTED_IMPORT_EXTENSIONS,
    maxImportFileSizeBytes: MAX_IMPORT_FILE_SIZE_BYTES,
    maxImportRows: MAX_IMPORT_ROWS,
    ensureEditableKeys,
    keyOfRow,
    markDeclRowsReviewed,
    unmarkDeclRowsReviewed,
    formatDateRangeLabel,
    formatDisplayDate,
    toDateInputValue,
  });
  const { coFilterActive, coFilterMatches } = useMemo(
    () =>
      buildDataImporterCoFilterSummary({
        rawRows,
        coFilterMode,
        coThreshold,
        getCoLineCount: coLineCount,
      }),
    [rawRows, coFilterMode, coThreshold],
  );
  const { queryFilterControlsProps } = useDataImporterQueryFilters({
    query,
    mainSearchHelpTextId,
    datePreset,
    dateRangePresets: DATE_RANGE_PRESETS,
    searchRange,
    filterNoStaff,
    filterNoTeam,
    coFilterMode,
    coFilterMin,
    coFilterActive,
    coFilterMatches,
    coFilterOptions: CO_FILTER_OPTIONS,
    setQuery,
    setPage,
    setDatePreset,
    setSearchRange,
    setFilterNoStaff,
    setFilterNoTeam,
    setCoFilterMode,
    setCoFilterMin,
  });

  return {
    actor,
    rules,
    setRules,
    rowSaveStatus,
    setRowSaveStatus,
    rowHistoryExpanded,
    rowHistoryEntries,
    setRowHistoryExpanded,
    setRowHistoryEntries,
    refreshRowHistory,
    handleToggleHistory,
    isReadOnlyForEdits,
    canReviewAlerts,
    canViewSavedRows,
    agencyOptions,
    blockedEditNoticeRef,
    canAutoReconcile,
    editingRestrictionMessage,
    isAdminRole,
    isRowEditable,
    memberTeamMap,
    rosterTeams,
    sanitizeRowUpdates,
    columnWidths,
    columnConfigOpen,
    columnDraftHidden,
    columnDraftError,
    columnHiddenSet,
    totalBaseColumns,
    totalConfigColumns,
    visibleColumnCount,
    setColumnConfigOpen,
    setColumnDraftHidden,
    setColumnDraftError,
    registerHeaderRef,
    renderResizeHandle,
    handleToggleColumnDraft,
    handleApplyColumnConfig,
    handleResetColumnConfig,
    reviewLockMessage,
    isRowReviewLocked,
    filterDuplicate11,
    setFilterDuplicate11,
    deletedRowCount,
    baseFilterInputs,
    normalizedFilters,
    deletedDialogOpen,
    hardDeletedLoading,
    hardDeletedError,
    deletedEntries,
    softDeletedCount,
    hardDeletedCount,
    deletedTotalCount,
    deletedRangeLabel,
    openDeletedDialog,
    handleDeletedDialogOpenChange,
    handleHardDeletedRetry,
    shouldUseServerSearch,
    pageResetKey,
    effectivePreviewRows,
    canUploadFiles,
    canOverwriteData,
    importPreview,
    pageSize,
    setPageSize,
    pageSizeMode,
    setPageSizeMode,
    pageSizeCustomInput,
    setPageSizeCustomInput,
    viewMode,
    setViewMode,
    freezeColumnsEnabled,
    setFreezeColumnsEnabled,
    cardGridColumns,
    setCardGridColumns,
    handleOpenColumnConfig,
    handleToolbarViewModeChange,
    handleToolbarFreezeColumnsEnabledChange,
    handleToolbarCardGridColumnsChange,
    handleToolbarPageSizeSelect,
    handleToolbarPageSizeCustomInput,
    handleToolbarToggleShowDeletedRows,
    handleOverwriteToggle,
    filterEditableKeys,
    filterHardDeleteKeys,
    ensureEditableKeys,
    ensureHardDeleteKeys,
    selectedPresetId,
    appliedPreset,
    appliedPresetUpdatedAt,
    presetSaving,
    presetBusy,
    savedPresets,
    presetLoading,
    presetError,
    clearPresetError,
    handleSelectPreset,
    handleApplySelectedPreset,
    handleSavePresetAsNew,
    handleOverwriteSelectedPreset,
    handleDeleteSelectedPreset,
    handleRefreshPresetList,
    licenseExcludeSet,
    licenseAgencyExcludeMap,
    getLicenseExcludeSetForRow,
    summarizeLicenseSnapshot,
    coCodeConfig,
    coCodeForm,
    setCoCodeForm,
    coCodeLoading,
    coCodeSaving,
    coCodeError,
    coCodeMessage,
    handleSaveCoCodeConfig,
    handleResetCoCodeForm,
    handleRefreshCoCodeConfig,
    coCodeUpdatedLabel,
    coDiscrepancyState,
    coDiscrepancyForm,
    setCoDiscrepancyForm,
    coDiscrepancyRange,
    setCoDiscrepancyRange,
    coDiscrepancyLoading,
    coDiscrepancySaving,
    coDiscrepancyRunning,
    coDiscrepancyError,
    coDiscrepancyMessage,
    handleSaveCoDiscrepancyConfig,
    handleResetCoDiscrepancyForm,
    handleRunCoDiscrepancy,
    handleRefreshCoDiscrepancy,
    coMismatchKeySet,
    coMismatchPreview,
    coMismatchCount,
    coCheckedCount,
    coMismatchLimited,
    coDiscrepancyRangeLabel,
    coDiscrepancyLastRunLabel,
    coDiscrepancyStatusLabel,
    loadSavedRows,
    syncConfig,
    syncForm,
    setSyncForm,
    syncLoading,
    syncRunning,
    syncMessage,
    syncError,
    manualRange,
    handleManualRangeChange,
    alertSummary,
    alertLoading,
    statusInfo,
    statusLoading,
    statusError,
    previewRows,
    previewLimited,
    previewLoading,
    previewError,
    previewRangeInfo,
    previewRangeLabel,
    mstFilterNotice,
    fetchSyncConfig,
    fetchSyncStatus,
    fetchAlerts,
    handleSaveSyncConfig,
    handleRunSync,
    handlePreviewSync,
    handleFileChange,
    handleImport,
    applyRangePreset,
    handleRefreshAlerts,
    handleMarkReviewed,
    handleUnmarkReviewed,
    outstandingAlerts,
    summaryCards,
    lastAlertEvaluated,
    syncLastRunLabel,
    lastSyncSummary,
    lastSyncRangeLabel,
    lastSyncRunAtLabel,
    queryFilterControlsProps,
  };
}
