// src/components/dataImporter/useDataImporterContainerProps.js

import React, { useCallback, useRef, useState } from "react";

import { sortDeclRows, pushAuditLog, IMPORT_AUX_COLUMN_IDS, saveDeclRows } from "@/lib/store.js";
import useDataImporterBaselineSnapshot from "@/components/dataImporter/useDataImporterBaselineSnapshot.js";
import useDataImporterContainerWidth from "@/components/dataImporter/useDataImporterContainerWidth.js";
import useDataImporterDuplicateWorkflow from "@/components/dataImporter/useDataImporterDuplicateWorkflow.js";
import useDataImporterResultsSurface from "@/components/dataImporter/useDataImporterResultsSurface.jsx";
import useDataImporterSessionController from "@/components/dataImporter/useDataImporterSessionController.js";
import {
  ACCEPTED_IMPORT_EXTENSIONS,
  AUX_COLUMN_LABELS,
  CARD_GRID_COLUMN_OPTIONS,
  CARD_GRID_MIN_WIDTH,
  CO_FILTER_OPTIONS,
  COLUMN_CONFIG_OPTIONS,
  DATE_RANGE_PRESETS,
  DECL_HISTORY_ENTRY_LIMIT,
  DEFAULT_CARD_GRID_COLUMNS,
  DUPLICATE_MERGE_FIELDS,
  FILTER_PRESET_SCOPE,
  FREEZE_COLUMNS_STORAGE_KEY,
  FROZEN_COLUMN_KEYS,
  GRID_COLUMNS_STORAGE_KEY,
  IMPORT_ERROR_REASON_LABELS,
  IMPORT_TABLE_COLUMNS,
  MAX_IMPORT_FILE_SIZE_BYTES,
  MAX_IMPORT_ROWS,
  PAGE_SIZE_OPTIONS,
  PAGE_SIZE_STORAGE_KEY,
  RANGE_PRESETS,
  SERVER_SEARCH_THRESHOLD,
  SENSITIVE_COLUMN_SET,
  VIEW_MODES,
  VIEW_MODE_STORAGE_KEY,
} from "@/components/dataImporter/dataImporterConfig.js";
import {
  applyMergeField,
  clearDuplicateReviewFlags,
  formatDeclarationLabel,
} from "@/components/dataImporter/dataImporterDuplicateReviewUtils.js";
import createDataImporterDialogProps from "@/components/dataImporter/dataImporterDialogProps.js";
import { createDuplicateDiffGroups } from "@/components/dataImporter/dataImporterDuplicateDiffUtils.js";
import createDataImporterContainerProps from "@/components/dataImporter/dataImporterContainerProps.js";
import createDataImporterShellProps from "@/components/dataImporter/dataImporterShellProps.js";
import createDataImporterSyncPanelProps from "@/components/dataImporter/dataImporterSyncPanelProps.js";

import { coLabel, coLineCount } from "../../../packages/domain/src/co.js";

import { formatDisplayDate } from "../../../packages/domain/src/format.js";

function getRowKey(row) {
  const soTk = (row?.so_tk || "").toString();

  const nhanh = (row?.nhanh || "").toString();

  return `${soTk}_${nhanh}`;
}
const CARD_SURFACE_CLASS =
  "rounded border border-[color:var(--ds-border-subtle)] bg-[color:var(--ds-surface-card)] shadow-sm";

const ZEBRA_TABLE_BODY_CLASS =
  "[&_tbody_tr:nth-child(odd)]:bg-[color:var(--ds-surface-card)] [&_tbody_tr:nth-child(even)]:bg-[color:var(--ds-surface-muted)]";

export default function useDataImporterContainerProps({
  canEdit = true,

  canImportUpload = false,

  currentUser = null,

  canManageSync = false,

  canManageAlerts = false,

  allowAdminUploadOverride = true,
}) {
  const rootRef = useRef(null);

  const fileRef = useRef(null);
  const mainSearchHelpTextId = React.useId();

  const containerWidth = useDataImporterContainerWidth({ rootRef });

  const [rawRows, setRawRows] = useState([]); // dữ liệu xem trước (đã map)

  const [showDeletedRows, setShowDeletedRows] = useState(false);

  const [query, setQuery] = useState("");

  const [quickMST, setQuickMST] = useState("");

  const [quickCompany, setQuickCompany] = useState("");

  const [statusFilters, setStatusFilters] = useState([]);

  const [page, setPage] = useState(1);

  const [mode, setMode] = useState("saved"); // saved | preview

  const [selectedFile, setSelectedFile] = useState("");
  const [previewSource, setPreviewSource] = useState(null);
  const [syncPreviewMeta, setSyncPreviewMeta] = useState(null);

  const keyOfRow = useCallback((row) => getRowKey(row), []);

  const { rowDiffMap, updateBaselineSnapshot, commitRowToBaseline } =
    useDataImporterBaselineSnapshot({
      mode,
      rawRows,
      keyOfRow,
    });
  const [selectedKeys, setSelectedKeys] = useState([]);
  const [hasUnsaved, setHasUnsaved] = useState(false);

  // Tuỳ chọn

  const [overwrite, setOverwrite] = useState(false); // Ghi đè toàn bộ

  const [upsert11, setUpsert11] = useState(true); // Upsert theo 11 số đầu (nếu có dùng merge cục bộ)

  const [autoAssignStaff, setAutoAssignStaff] = useState(true); // Tự gán nhân viên theo MST nếu trống
  const {
    actor,
    rules,
    rowSaveStatus,
    setRowSaveStatus,
    rowHistoryExpanded,
    rowHistoryEntries,
    refreshRowHistory,
    handleToggleHistory,
    isReadOnlyForEdits,
    canReviewAlerts,
    canViewSavedRows,
    agencyOptions,
    blockedEditNoticeRef,
    canAutoReconcile,
    editingRestrictionMessage,
    isAdminRole,
    isRowEditable,
    memberTeamMap,
    rosterTeams,
    sanitizeRowUpdates,
    columnWidths,
    columnConfigOpen,
    columnDraftHidden,
    columnDraftError,
    columnHiddenSet,
    totalBaseColumns,
    totalConfigColumns,
    visibleColumnCount,
    setColumnConfigOpen,
    registerHeaderRef,
    renderResizeHandle,
    handleToggleColumnDraft,
    handleApplyColumnConfig,
    handleResetColumnConfig,
    reviewLockMessage,
    isRowReviewLocked,
    filterDuplicate11,
    setFilterDuplicate11,
    deletedRowCount,
    normalizedFilters,
    deletedDialogOpen,
    hardDeletedLoading,
    hardDeletedError,
    deletedEntries,
    softDeletedCount,
    hardDeletedCount,
    deletedTotalCount,
    deletedRangeLabel,
    openDeletedDialog,
    handleDeletedDialogOpenChange,
    handleHardDeletedRetry,
    shouldUseServerSearch,
    pageResetKey,
    effectivePreviewRows,
    canUploadFiles,
    canOverwriteData,
    importPreview,
    pageSize,
    pageSizeMode,
    pageSizeCustomInput,
    viewMode,
    freezeColumnsEnabled,
    cardGridColumns,
    handleOpenColumnConfig,
    handleToolbarViewModeChange,
    handleToolbarFreezeColumnsEnabledChange,
    handleToolbarCardGridColumnsChange,
    handleToolbarPageSizeSelect,
    handleToolbarPageSizeCustomInput,
    handleToolbarToggleShowDeletedRows,
    handleOverwriteToggle,
    filterEditableKeys,
    filterHardDeleteKeys,
    ensureEditableKeys,
    ensureHardDeleteKeys,
    selectedPresetId,
    appliedPreset,
    appliedPresetUpdatedAt,
    presetSaving,
    presetBusy,
    savedPresets,
    presetLoading,
    presetError,
    clearPresetError,
    handleSelectPreset,
    handleApplySelectedPreset,
    handleSavePresetAsNew,
    handleOverwriteSelectedPreset,
    handleDeleteSelectedPreset,
    handleRefreshPresetList,
    licenseExcludeSet,
    licenseAgencyExcludeMap,
    getLicenseExcludeSetForRow,
    summarizeLicenseSnapshot,
    coCodeConfig,
    coCodeForm,
    setCoCodeForm,
    coCodeLoading,
    coCodeSaving,
    coCodeError,
    coCodeMessage,
    handleSaveCoCodeConfig,
    handleResetCoCodeForm,
    handleRefreshCoCodeConfig,
    coCodeUpdatedLabel,
    coDiscrepancyState,
    coDiscrepancyForm,
    setCoDiscrepancyForm,
    coDiscrepancyRange,
    setCoDiscrepancyRange,
    coDiscrepancyLoading,
    coDiscrepancySaving,
    coDiscrepancyRunning,
    coDiscrepancyError,
    coDiscrepancyMessage,
    handleSaveCoDiscrepancyConfig,
    handleResetCoDiscrepancyForm,
    handleRunCoDiscrepancy,
    handleRefreshCoDiscrepancy,
    coMismatchKeySet,
    coMismatchPreview,
    coMismatchCount,
    coCheckedCount,
    coMismatchLimited,
    coDiscrepancyRangeLabel,
    coDiscrepancyLastRunLabel,
    coDiscrepancyStatusLabel,
    loadSavedRows,
    syncConfig,
    syncForm,
    setSyncForm,
    syncLoading,
    syncRunning,
    syncMessage,
    syncError,
    manualRange,
    handleManualRangeChange,
    alertSummary,
    alertLoading,
    statusInfo,
    statusLoading,
    statusError,
    previewRows,
    previewLimited,
    previewLoading,
    previewError,
    previewRangeInfo,
    previewRangeLabel,
    mstFilterNotice,
    syncPreflightChecks,
    syncPreflightSummary,
    syncActivityLog,
    syncResumeJob,
    syncResumeLabel,
    fetchSyncConfig,
    fetchSyncStatus,
    fetchAlerts,
    handleSaveSyncConfig,
    handleRunSync,
    handleResumeSync,
    handlePreviewSync,
    handleFileChange,
    handleImport,
    applyRangePreset,
    handleRefreshAlerts,
    handleMarkReviewed,
    handleUnmarkReviewed,
    alertEntries,
    summaryCards,
    lastAlertEvaluated,
    syncLastRunLabel,
    lastSyncSummary,
    lastSyncRangeLabel,
    lastSyncRunAtLabel,
    queryFilterControlsProps,
  } = useDataImporterSessionController({
    currentUser,
    canEdit,
    canImportUpload,
    canManageSync,
    canManageAlerts,
    allowAdminUploadOverride,
    mainSearchHelpTextId,
    fileRef,
    rawRows,
    setRawRows,
    showDeletedRows,
    setShowDeletedRows,
    query,
    setQuery,
    quickMST,
    setQuickMST,
    quickCompany,
    setQuickCompany,
    statusFilters,
    setStatusFilters,
    setPage,
    mode,
    setMode,
     selectedFile,
     setSelectedFile,
     previewSource,
     setPreviewSource,
     syncPreviewMeta,
     setSyncPreviewMeta,
     selectedKeys,
    setSelectedKeys,
    hasUnsaved,
    setHasUnsaved,
    overwrite,
    setOverwrite,
    upsert11,
    autoAssignStaff,
    updateBaselineSnapshot,
    keyOfRow,
  });

  const {
    duplicate11Summary,
    duplicate11GroupCount,
    duplicate11TotalRows,
    duplicate11DuplicatesSet,
    duplicate11KeeperSet,
    duplicate11Details,
    hasDuplicate11Rows,
    lastSyncFetched,
    lastSyncInserted,
    lastSyncUpdated,
    lastSyncSkipped,
    lastSyncTotal,
    updatedDeclarations,
    updatedKeySet,
    updatedPreview,
    showUpdatedBanner,
    handleSelectUpdated,
    handleSelectCoMismatches,
    handleToggleDuplicateFilter,
    duplicateDiffState,
    duplicateDiffGroup,
    duplicateDiffBaseItem,
    duplicateDiffCompareItem,
    duplicateDiffGroups,
    duplicateDiffChangedCount,
    duplicateDiffGroupLabel,
    duplicateDiffBaseLabel,
    duplicateDiffCompareLabel,
    handleOpenDuplicateDiff,
    handleCloseDuplicateDiff,
    handleChangeDuplicateDiffBase,
    handleChangeDuplicateDiffCompare,
    handleSwapDuplicateDiff,
    handleDuplicateDiffOpenChange,
    duplicateReviewOpen,
    duplicateReviewConfirmed,
    duplicate11Plan,
    duplicate11PlanHasActions,
    duplicate11PlannedDeleteGroups,
    duplicate11PlannedReviewGroups,
    duplicate11PlannedRemovalCount,
    setDuplicateReviewConfirmed,
    handleChangeDuplicateKeeper,
    handleChangeDuplicateMerge,
    handleChangeDuplicateResolution,
    handleChangeDuplicateNote,
    handleDeleteDuplicates11,
    handleCloseDuplicateReview,
    handleDuplicateReviewOpenChange,
    handleConfirmDuplicateRemoval,
  } = useDataImporterDuplicateWorkflow({
    rawRows,
    keyOfRow,
    lastSyncSummary,
    mode,
    coMismatchKeySet,
    setSelectedKeys,
    setPage,
    setFilterDuplicate11,
    summarizeLicenseSnapshot,
    coLabel,
    coLineCount,
    createDuplicateDiffGroups,
    formatDeclarationLabel,
    actor,
    isReadOnlyForEdits,
    isAdminRole,
    editingRestrictionMessage,
    duplicateMergeFields: DUPLICATE_MERGE_FIELDS,
    isRowEditable,
    clearDuplicateReviewFlags,
    applyMergeField,
    sortDeclRows,
    saveDeclRows,
    pushAuditLog,
    loadSavedRows,
    fetchAlerts,
  });
  const {
    appliedCardColumns,
    cardResultsProps,
    deleteEnabled,
    effectiveCardColumns,
    filteredKeys,
    handleAutoApplyLicenseExclusion,
    handleSaveAll,
    lastSyncSummaryCard,
    maxPage,
    safePage,
    selectionEnabled,
    selectionActionsProps,
    serverSearchState,
    tableResultsProps,
    total,
  } = useDataImporterResultsSurface({
    actor,
    agencyOptions,
    blockedEditNoticeRef,
    canAutoReconcile,
    canEdit,
    canManageAlerts,
    canReviewAlerts,
    cardGridColumns,
    coCodeConfig,
    coDiscrepancyForm,
    coDiscrepancyState,
    coMismatchKeySet,
    duplicate11KeeperSet,
    duplicate11DuplicatesSet,
    columnHiddenSet,
    columnWidths,
    commitRowToBaseline,
    containerWidth,
    duplicate11Summary,
    editingRestrictionMessage,
    ensureEditableKeys,
    ensureHardDeleteKeys,
    fetchAlerts,
    filterEditableKeys,
    filterHardDeleteKeys,
    freezeColumnsEnabled,
    getLicenseExcludeSetForRow,
    handleMarkReviewed,
    handleToggleHistory,
    handleUnmarkReviewed,
    isAdminRole,
    isReadOnlyForEdits,
    isRowEditable,
    isRowReviewLocked,
    keyOfRow,
    licenseAgencyExcludeMap,
    licenseExcludeSet,
    loadSavedRows,
    memberTeamMap,
    mode,
    normalizedFilters,
    page,
    pageResetKey,
    pageSize,
    pushAuditLog,
    rawRows,
    refreshRowHistory,
    registerHeaderRef,
    renderResizeHandle,
    reviewLockMessage,
    rootRef,
    rosterTeams,
    rowDiffMap,
    rowHistoryEntries,
    rowHistoryExpanded,
    rowSaveStatus,
    rules,
    sanitizeRowUpdates,
    selectedKeys,
    setHasUnsaved,
    setPage,
    setRawRows,
    setRowSaveStatus,
    setSelectedKeys,
    shouldUseServerSearch,
    showDeletedRows,
    summarizeLicenseSnapshot,
    syncConfig,
    updatedKeySet,
    visibleColumnCount,
    lastSyncFetched,
    lastSyncInserted,
    lastSyncRangeLabel,
    lastSyncRunAtLabel,
    lastSyncSkipped,
    lastSyncSummary,
    lastSyncTotal,
    lastSyncUpdated,
  });

  const {
    coCodeConfigProps,
    monitoringCoDiscrepancyProps,
    monitoringAlertsProps,
    syncConfigPanelProps,
  } = createDataImporterSyncPanelProps({
    canManageSync,
    isAdminRole,
    alertSummary,
    alertEntries,
    alertLoading,
    lastAlertEvaluated,
    coCodeLoading,
    coCodeSaving,
    coCodeError,
    coCodeMessage,
    coCodeForm,
    handleRefreshCoCodeConfig,
    handleSaveCoCodeConfig,
    handleResetCoCodeForm,
    setCoCodeForm,
    coCodeUpdatedLabel,
    coDiscrepancyRange,
    setCoDiscrepancyRange,
    handleRunCoDiscrepancy,
    handleRefreshCoDiscrepancy,
    coDiscrepancyRunning,
    coDiscrepancyLoading,
    coDiscrepancyError,
    coDiscrepancyMessage,
    coDiscrepancyStatusLabel,
    coDiscrepancyLastRunLabel,
    coMismatchCount,
    coCheckedCount,
    coDiscrepancyForm,
    setCoDiscrepancyForm,
    coDiscrepancySaving,
    handleSaveCoDiscrepancyConfig,
    handleResetCoDiscrepancyForm,
    coDiscrepancyRangeLabel,
    coMismatchLimited,
    coMismatchPreview,
    coMismatchKeyCount: coMismatchKeySet.size,
    onSelectMismatches: handleSelectCoMismatches,
    handleRefreshAlerts,
    syncLastRunLabel,
    syncConfig,
    fetchSyncConfig,
    fetchSyncStatus,
    handleSaveSyncConfig,
    syncLoading,
    statusLoading,
    syncForm,
    setSyncForm,
    statusInfo,
    statusError,
    lastSyncSummaryCard,
    rangePresets: RANGE_PRESETS,
    manualRange,
    onApplyRangePreset: applyRangePreset,
    handleManualRangeChange,
    syncRunning,
    previewLoading,
    handlePreviewSync,
    handleRunSync,
    mstFilterNotice,
    previewRangeInfo,
    previewRangeLabel,
    previewLimited,
    previewError,
    previewRows,
    syncPreflightChecks,
    syncPreflightSummary,
    syncActivityLog,
    syncResumeJob,
    syncResumeLabel,
    formatDisplayDate,
    syncMessage,
    syncError,
    handleResumeSync,
    cardSurfaceClass: CARD_SURFACE_CLASS,
    mode,
    previewSource,
  });

  const { columnDraftVisibleCount, workflowGuideProps, fileActionsProps, listControlsPanelProps } =
    createDataImporterShellProps({
      columnDraftHidden,
      totalConfigColumns,
      isReadOnlyForEdits,
      mode,
      effectivePreviewRows,
      importPreview,
      previewSource,
      canEdit,
      rawRowsLength: rawRows.length,
      selectedFile,
      canViewSavedRows,
      canUploadFiles,
      canManageSync,
      syncPreviewRows: previewRows,
      previewLoading,
      syncRunning,
      fileInputRef: fileRef,
      onFileChange: handleFileChange,
      onImport: handleImport,
      onPreviewSync: handlePreviewSync,
      onRunSync: handleRunSync,
      onLoadSavedRows: loadSavedRows,
      onOpenDeletedList: openDeletedDialog,
      selectedPresetId,
      savedPresets,
      presetBusy,
      presetSaving,
      presetLoading,
      presetError,
      appliedPreset,
      appliedPresetUpdatedAt,
      onSelectPreset: handleSelectPreset,
      onApplySelectedPreset: handleApplySelectedPreset,
      onSavePresetAsNew: handleSavePresetAsNew,
      onOverwriteSelectedPreset: handleOverwriteSelectedPreset,
      onDeleteSelectedPreset: handleDeleteSelectedPreset,
      onRefreshPresetList: handleRefreshPresetList,
      onClearPresetError: clearPresetError,
      filterDuplicate11,
      hasDuplicate11Rows,
      duplicate11GroupCount,
      duplicate11PlannedRemovalCount,
      duplicate11PlannedReviewGroups,
      duplicate11TotalRows,
      filteredKeyCount: filteredKeys.length,
      canAutoReconcile,
      onToggleDuplicateFilter: handleToggleDuplicateFilter,
      onDeleteDuplicates11: handleDeleteDuplicates11,
      onAutoApplyLicenseExclusion: handleAutoApplyLicenseExclusion,
      deleteEnabled,
      shouldUseServerSearch,
      serverSearchState,
      total,
      safePage,
      maxPage,
      viewMode,
      freezeColumnsEnabled,
      appliedCardColumns,
      effectiveCardColumns,
      cardGridColumnOptions: CARD_GRID_COLUMN_OPTIONS,
      pageSize,
      pageSizeMode,
      pageSizeCustomInput,
      pageSizeOptions: PAGE_SIZE_OPTIONS,
      showDeletedRows,
      deletedRowCount,
      onChangeViewMode: handleToolbarViewModeChange,
      onChangeFreezeColumnsEnabled: handleToolbarFreezeColumnsEnabledChange,
      onChangeCardGridColumns: handleToolbarCardGridColumnsChange,
      onChangePageSizeSelect: handleToolbarPageSizeSelect,
      onChangePageSizeCustomInput: handleToolbarPageSizeCustomInput,
      onToggleShowDeletedRows: handleToolbarToggleShowDeletedRows,
      setPage,
      onSaveAll: handleSaveAll,
      autoAssignStaff,
      upsert11,
      overwrite,
      canOverwriteData,
      query,
      visibleColumnCount,
      totalBaseColumns,
      selectionEnabled,
      hasUnsaved,
      queryFilterControlsProps,
      selectionActionsProps,
      onAutoAssignStaffChange: setAutoAssignStaff,
      onUpsert11Change: setUpsert11,
      onOverwriteToggle: handleOverwriteToggle,
      onOpenColumnConfig: handleOpenColumnConfig,
    });
  const {
    deletedDialog,
    columnConfigDialog,
    duplicateDiffDialog,
    duplicateReviewDialog,
    updatedRowsBanner,
  } = createDataImporterDialogProps({
    deletedDialogOpen,
    handleDeletedDialogOpenChange,
    deletedRangeLabel,
    deletedTotalCount,
    softDeletedCount,
    hardDeletedCount,
    hardDeletedLoading,
    hardDeletedError,
    handleHardDeletedRetry,
    deletedEntries,
    zebraTableBodyClass: ZEBRA_TABLE_BODY_CLASS,
    columnConfigOpen,
    setColumnConfigOpen,
    columnConfigOptions: COLUMN_CONFIG_OPTIONS,
    columnDraftHidden,
    columnDraftVisibleCount,
    totalConfigColumns,
    isAdminRole,
    sensitiveColumnSet: SENSITIVE_COLUMN_SET,
    columnDraftError,
    handleToggleColumnDraft,
    handleResetColumnConfig,
    handleApplyColumnConfig,
    duplicateDiffState,
    handleDuplicateDiffOpenChange,
    duplicateDiffGroup,
    duplicateDiffGroupLabel,
    duplicateDiffBaseLabel,
    duplicateDiffCompareLabel,
    duplicateDiffBaseItem,
    duplicateDiffCompareItem,
    duplicateDiffChangedCount,
    duplicateDiffGroups,
    handleChangeDuplicateDiffBase,
    handleChangeDuplicateDiffCompare,
    handleSwapDuplicateDiff,
    handleCloseDuplicateDiff,
    duplicateReviewOpen,
    handleDuplicateReviewOpenChange,
    duplicate11Details,
    duplicate11Plan,
    duplicate11PlanHasActions,
    duplicate11PlannedRemovalCount,
    duplicate11PlannedDeleteGroups,
    duplicate11PlannedReviewGroups,
    duplicateReviewConfirmed,
    setDuplicateReviewConfirmed,
    duplicateMergeFields: DUPLICATE_MERGE_FIELDS,
    handleChangeDuplicateKeeper,
    handleOpenDuplicateDiff,
    handleChangeDuplicateMerge,
    handleChangeDuplicateResolution,
    handleChangeDuplicateNote,
    handleCloseDuplicateReview,
    handleConfirmDuplicateRemoval,
    showUpdatedBanner,
    lastSyncUpdated,
    lastSyncRunAtLabel,
    updatedPreview,
    updatedDeclarations,
    formatDeclarationLabel,
    handleSelectUpdated,
    clearSelection: () => setSelectedKeys([]),
  });
  const containerProps = createDataImporterContainerProps({
    rootRef,
    canUploadFiles,
    isReadOnlyForEdits,
    canManageAlerts,
    isAdminRole,
    mode,
    previewSource,
    deletedDialog,
    columnConfigDialog,
    duplicateDiffDialog,
    duplicateReviewDialog,
    workflowGuideProps,
    summaryCards,
    cardSurfaceClass: CARD_SURFACE_CLASS,
    updatedRowsBanner,
    syncConfigPanelProps,
    coCodeConfigProps,
    monitoringCoDiscrepancyProps,
    monitoringAlertsProps,
    formatDeclarationLabel,
    formatDisplayDate,
    fileActionsProps,
    importPreview,
    errorReasonLabels: IMPORT_ERROR_REASON_LABELS,
    listControlsPanelProps,
    viewMode,
    tableResultsProps,
    cardResultsProps,
  });

  return containerProps;
}
